# Generated by Django 5.2.16 on 2026-07-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_property_address_property_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='available_rooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='property',
            name='gender',
            field=models.CharField(choices=[('BOYS', 'Boys'), ('GIRLS', 'Girls'), ('UNISEX', 'Unisex')], default='UNISEX', max_length=10),
        ),
        migrations.AddField(
            model_name='property',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='property_type',
            field=models.CharField(choices=[('HOSTEL', 'Hostel'), ('PG', 'PG'), ('APARTMENT', 'Apartment')], default='HOSTEL', max_length=20),
        ),
    ]
