# Generated by Django 5.2.16 on 2026-07-26 19:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0004_property_latitude_property_longitude'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorite_properties', to=settings.AUTH_USER_MODEL),
        ),
    ]
